language: python
python:
    - 2.7
before_install: pip freeze
install:
    - python setup.py install
    - pip install -U "pip>=1.4" "setuptools>=0.9" "wheel>=0.21" "python-dateutil==1.5" "ujson" "urllib3"
    - python setup.py sdist bdist bdist_egg bdist_wheel
script:
    - python test_unittest.py
